site_name: Scarif.xyz
theme: dracula
nav:
  - Introduction:
    - 'Project Overview': 'introduction/project-overview.md'
    - 'Idea and Vision': 'introduction/idea-and-vision.md'
  - Getting Started:
    - 'Prerequisites': 'getting-started/prerequisites.md'
    - 'Installation and Setup': 'getting-started/installation-and-setup.md'
    - 'Quick Start Guide': 'getting-started/quick-start-guide.md'
  - Architecture:
    - 'System Architecture': 'architecture/system-architecture.md'
    - 'Contract Design': 'architecture/contract-design.md'
  - Usage:
    - 'User Guide': 'usage/user-guide.md'
    - 'API Reference': 'usage/api-reference.md'
  - Development:
    - 'Setup and Tooling': 'development/setup-and-tooling.md'
    - 'Contribution Guidelines': 'development/contribution-guidelines.md'
  - Examples and Tutorials:
    - 'Walkthroughs': 'examples-and-tutorials/walkthroughs.md'
    - 'Code Examples': 'examples-and-tutorials/code-examples.md'
  - Advanced Topics:
    - 'Extending the Factory Contract': 'advanced-topics/extending-the-factory-contract.md'
    - 'Security Considerations': 'advanced-topics/security-considerations.md'
  - FAQs: 'faqs.md'
  - Resources:
    - 'Glossary': 'resources/glossary.md'
    - 'Further Reading': 'resources/further-reading.md'
  - About:
    - 'The Team': 'about/the-team.md'
    - 'Contact and Support': 'about/contact-and-support.md'
  - Changelog: 'changelog.md'
